//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorException
    {
        public int Id { get; set; }
        public System.DateTime ExceptionTime { get; set; }
        public string ExceptionTitle { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string Source { get; set; }
        public string HelpLink { get; set; }
        public Nullable<int> HResult { get; set; }
    }
}
